// Cities array for location autocomplete - lazy loaded to reduce initial bundle size
export const cities = [
  // Alberta
  "Calgary, AB",
  "Edmonton, AB",
  "Red Deer, AB",
  "Lethbridge, AB",
  "Medicine Hat, AB",
  "Grande Prairie, AB",
  "Fort McMurray, AB",
  "Airdrie, AB",
  "St. Albert, AB",
  "Leduc, AB",
  "Spruce Grove, AB",
  "Cochrane, AB",
  "Okotoks, AB",
  "Canmore, AB",
  "Banff, AB",
  "Lloydminster, AB",
  "Camrose, AB",
  "Cold Lake, AB",
  "Brooks, AB",
  "Wetaskiwin, AB",
  "Fort Saskatchewan, AB",
  "Lacombe, AB",
  "Sylvan Lake, AB",
  "Strathmore, AB",
  "High River, AB",
  "Drumheller, AB",
  "Canmore, AB",
  "Jasper, AB",
  "Hinton, AB",
  "Whitecourt, AB",
  "Drayton Valley, AB",
  "Peace River, AB",
  "High Level, AB",
  "Slave Lake, AB",
  "Wainwright, AB",
  "Vegreville, AB",
  "Stony Plain, AB",
  "Beaumont, AB",
  "Devon, AB",
  "Fort Macleod, AB",
  "Cardston, AB",
  "Taber, AB",
  "Pincher Creek, AB",
  "Crowsnest Pass, AB",
  "Claresholm, AB",
  "Nanton, AB",
  "Vulcan, AB",
  "Hanna, AB",
  "Oyen, AB",
  "Three Hills, AB",
  "Innisfail, AB",
  "Olds, AB",
  "Carstairs, AB",
  "Crossfield, AB",
  "Blackfalds, AB",
  "Ponoka, AB",
  "Rimbey, AB",
  "Bashaw, AB",
  "Stettler, AB",
  "Castor, AB",
  "Coronation, AB",
  "Hanna, AB",
  "Oyen, AB",
  "Killam, AB",
  "Wetaskiwin, AB",
  "Millet, AB",
  "Leduc, AB",
  "Calmar, AB",
  "Thorsby, AB",
  "Warburg, AB",
  "Drayton Valley, AB",
  "Rimbey, AB",
  "Sundre, AB",
  "Caroline, AB",
  "Rocky Mountain House, AB",
  "Nordegg, AB",
  "Edson, AB",
  "Hinton, AB",
  "Jasper, AB",
  "Grande Cache, AB",
  "Fox Creek, AB",
  "Valleyview, AB",
  "Grande Prairie, AB",
  "Beaverlodge, AB",
  "Fairview, AB",
  "Grimshaw, AB",
  "Manning, AB",
  "High Level, AB",
  "La Crête, AB",
  "Fort Vermilion, AB",
  "Rainbow Lake, AB",
  "Zama City, AB",
  "Fort Chipewyan, AB",
  "Fort McMurray, AB",
  "Conklin, AB",
  "Anzac, AB",
  "Janvier, AB",
  "Lac La Biche, AB",
  "Boyle, AB",
  "Athabasca, AB",
  "Westlock, AB",
  "Barrhead, AB",
  "Morinville, AB",
  "Bon Accord, AB",
  "Gibbons, AB",
  "Redwater, AB",
  "Lamont, AB",
  "Mundare, AB",
  "Vegreville, AB",
  "Viking, AB",
  "Killam, AB",
  "Hardisty, AB",
  "Sedgewick, AB",
  "Camrose, AB",
  "Tofield, AB",
  "Beaver County, AB",
  // British Columbia
  "Vancouver, BC",
  "Victoria, BC",
  "Kelowna, BC",
  "Surrey, BC",
  "Burnaby, BC",
  "Richmond, BC",
  "Langley, BC",
  "Abbotsford, BC",
  "Coquitlam, BC",
  "Saanich, BC",
  "Delta, BC",
  "Kamloops, BC",
  "Nanaimo, BC",
  "Prince George, BC",
  "Chilliwack, BC",
  "Maple Ridge, BC",
  "New Westminster, BC",
  "Port Coquitlam, BC",
  "North Vancouver, BC",
  "West Vancouver, BC",
  "Penticton, BC",
  "Vernon, BC",
  "Salmon Arm, BC",
  "Courtenay, BC",
  "Campbell River, BC",
  "Duncan, BC",
  "Port Alberni, BC",
  "Summerland, BC",
  "West Kelowna, BC",
  "Keremeos, BC",
  "Osoyoos, BC",
  "Oliver, BC",
  "Peachland, BC",
  "Lake Country, BC",
  "Coldstream, BC",
  "Armstrong, BC",
  "Enderby, BC",
  "Revelstoke, BC",
  "Golden, BC",
  "Invermere, BC",
  "Fernie, BC",
  "Cranbrook, BC",
  "Nelson, BC",
  "Trail, BC",
  "Castlegar, BC",
  "Grand Forks, BC",
  "Merritt, BC",
  "Princeton, BC",
  "Hope, BC",
  "Agassiz, BC",
  "Harrison Hot Springs, BC",
  "Lillooet, BC",
  "Pemberton, BC",
  "Whistler, BC",
  "Squamish, BC",
  "Gibsons, BC",
  "Sechelt, BC",
  "Powell River, BC",
  "Parksville, BC",
  "Qualicum Beach, BC",
  "Port Hardy, BC",
  "Terrace, BC",
  "Kitimat, BC",
  "Prince Rupert, BC",
  "Smithers, BC",
  "Houston, BC",
  "Fort St. James, BC",
  "Dawson Creek, BC",
  "Fort Nelson, BC",
  "100 Mile House, BC",
  "Williams Lake, BC",
  "Quesnel, BC",
  "Burns Lake, BC",
  "Vanderhoof, BC",
  "Ashcroft, BC",
  "Cache Creek, BC",
  "Lytton, BC",
  "Boston Bar, BC",
  "Ladysmith, BC",
  "Chemainus, BC",
  "Lake Cowichan, BC",
  "Ucluelet, BC",
  "Tofino, BC",
  "Tumbler Ridge, BC",
  "Chetwynd, BC",
  "Hudson's Hope, BC",
  "McBride, BC",
  "Valemount, BC",
  "Creston, BC",
  "Nakusp, BC",
  "New Denver, BC",
  "Kaslo, BC",
  "Slocan, BC",
  "Rossland, BC",
  "Fruitvale, BC",
  "Montrose, BC",
  "Warfield, BC",
  "Greenwood, BC",
  "Midway, BC",
  "Rock Creek, BC",
  "Okanagan Falls, BC",
  "Kaleden, BC",
  "Naramata, BC",
  "Sicamous, BC",
  "Blind Bay, BC",
  "Sorrento, BC",
  "Chase, BC",
  "Clearwater, BC",
  "Barriere, BC",
  "Sun Peaks, BC",
  "Clinton, BC",
  "Lac La Hache, BC",
  "Horsefly, BC",
  "Wells, BC",
  "Barkerville, BC",
  "Telkwa, BC",
  "Hazelton, BC",
  "Stewart, BC",
  "Dease Lake, BC",
  "Atlin, BC",
  "Fort St. John, BC",
  "Chetwynd, BC",
  "Tumbler Ridge, BC",
  "Hudson's Hope, BC",
  "Cumberland, BC",
  "Comox, BC",
  "Black Creek, BC",
  "Campbell River, BC",
  "Port McNeill, BC",
  "Port Alice, BC",
  "Alert Bay, BC",
  "Sooke, BC",
  "Metchosin, BC",
  "North Saanich, BC",
  "Central Saanich, BC",
  "Sidney, BC",
  "Colwood, BC",
  "View Royal, BC",
  "Langford, BC",
  "Highlands, BC",
  "Esquimalt, BC",
  "Oak Bay, BC",
  "White Rock, BC",
  "Langley, BC",
  "Mission, BC",
  "Kent, BC",
  "Harrison Hot Springs, BC",
  "Pitt Meadows, BC",
  "Maple Ridge, BC",
  "Port Moody, BC",
  "Belcarra, BC",
  "Anmore, BC",
  "Bowen Island, BC",
  "Lions Bay, BC",
  "West Vancouver, BC",
  "North Vancouver, BC",
  "New Westminster, BC",
  "Burnaby, BC",
  "Coquitlam, BC",
  "Port Coquitlam, BC",
  "Surrey, BC",
  "Delta, BC",
  "Richmond, BC",
  "Vancouver, BC",
  "New Hazelton, BC",
  "Granisle, BC",
  "Fraser Lake, BC",
  "Fort Fraser, BC",
  "Bella Coola, BC",
  "Bella Bella, BC",
  "Masset, BC",
  "Queen Charlotte, BC",
  "Sandspit, BC",
  "Port Clements, BC",
  "Tahsis, BC",
  "Zeballos, BC",
  "Gold River, BC",
  "Sayward, BC",
  "Woss, BC",
  "Port Alice, BC",
  "Winter Harbour, BC",
  "Sointula, BC",
  "Alert Bay, BC",
  // Saskatchewan
  "Saskatoon, SK",
  "Regina, SK",
  "Prince Albert, SK",
  "Moose Jaw, SK",
  "Swift Current, SK",
  "Yorkton, SK",
  "North Battleford, SK",
  // Manitoba
  "Winnipeg, MB",
  "Brandon, MB",
  "Steinbach, MB",
  "Thompson, MB",
  "Portage la Prairie, MB",
  // Ontario
  "Toronto, ON",
  "Ottawa, ON",
  "Mississauga, ON",
  "Brampton, ON",
  "Hamilton, ON",
  "London, ON",
  "Markham, ON",
  "Vaughan, ON",
  "Kitchener, ON",
  "Windsor, ON",
  "Richmond Hill, ON",
  "Oakville, ON",
  "Burlington, ON",
  "Oshawa, ON",
  "St. Catharines, ON",
  "Cambridge, ON",
  "Guelph, ON",
  "Barrie, ON",
  "Kingston, ON",
  "Thunder Bay, ON",
  "Sudbury, ON",
  "Sault Ste. Marie, ON",
  "North Bay, ON",
  "Timmins, ON",
  "Orillia, ON",
  "Collingwood, ON",
  "Owen Sound, ON",
  "Stratford, ON",
  "Woodstock, ON",
  "Brantford, ON",
  "Niagara Falls, ON",
  "Welland, ON",
  "Fort Erie, ON",
  "Port Colborne, ON",
  "Grimsby, ON",
  "Stoney Creek, ON",
  "Ancaster, ON",
  "Dundas, ON",
  "Waterdown, ON",
  "Burlington, ON",
  "Milton, ON",
  "Georgetown, ON",
  "Acton, ON",
  "Orangeville, ON",
  "Shelburne, ON",
  "Alliston, ON",
  "Bradford, ON",
  "Newmarket, ON",
  "Aurora, ON",
  "King City, ON",
  "Bolton, ON",
  "Caledon, ON",
  "Vaughan, ON",
  "Maple, ON",
  "Concord, ON",
  "Thornhill, ON",
  "Markham, ON",
  "Unionville, ON",
  "Scarborough, ON",
  "Pickering, ON",
  "Ajax, ON",
  "Whitby, ON",
  "Oshawa, ON",
  "Bowmanville, ON",
  "Port Hope, ON",
  "Cobourg, ON",
  "Belleville, ON",
  "Trenton, ON",
  "Picton, ON",
  "Napanee, ON",
  "Kingston, ON",
  "Gananoque, ON",
  "Brockville, ON",
  "Prescott, ON",
  "Smiths Falls, ON",
  "Carleton Place, ON",
  "Almonte, ON",
  "Arnprior, ON",
  "Pembroke, ON",
  "Petawawa, ON",
  "Deep River, ON",
  "Renfrew, ON",
  "Barry's Bay, ON",
  "Madawaska, ON",
  "Ottawa, ON",
  "Kanata, ON",
  "Nepean, ON",
  "Orleans, ON",
  "Gloucester, ON",
  "Cornwall, ON",
  "Hawkesbury, ON",
  "Pembroke, ON",
  "North Bay, ON",
  "Sturgeon Falls, ON",
  "Mattawa, ON",
  "Temagami, ON",
  "New Liskeard, ON",
  "Haileybury, ON",
  "Kirkland Lake, ON",
  "Timmins, ON",
  "Iroquois Falls, ON",
  "Cochrane, ON",
  "Kapuskasing, ON",
  "Hearst, ON",
  "Smooth Rock Falls, ON",
  "Elliot Lake, ON",
  "Blind River, ON",
  "Thessalon, ON",
  "Sault Ste. Marie, ON",
  "Wawa, ON",
  "Marathon, ON",
  "Terrace Bay, ON",
  "Nipigon, ON",
  "Thunder Bay, ON",
  "Atikokan, ON",
  "Dryden, ON",
  "Vermilion Bay, ON",
  "Kenora, ON",
  "Sioux Lookout, ON",
  "Red Lake, ON",
  "Geraldton, ON",
  "Longlac, ON",
  "Nakina, ON",
  "Parry Sound, ON",
  "Huntsville, ON",
  "Bracebridge, ON",
  "Gravenhurst, ON",
  "Port Carling, ON",
  "Bala, ON",
  "Mindemoya, ON",
  "Little Current, ON",
  "Gore Bay, ON",
  "Manitoulin Island, ON",
  "Espanola, ON",
  "Sudbury, ON",
  "Capreol, ON",
  "Levack, ON",
  "Lively, ON",
  "Chelmsford, ON",
  "Hanmer, ON",
  "St. Charles, ON",
  "Sturgeon Falls, ON",
  "West Nipissing, ON",
  "Temiskaming Shores, ON",
  "Cobalt, ON",
  "Latchford, ON",
  "Sarnia, ON",
  "Petrolia, ON",
  "Wallaceburg, ON",
  "Chatham, ON",
  "Blenheim, ON",
  "Ridgetown, ON",
  "Leamington, ON",
  "Kingsville, ON",
  "Essex, ON",
  "Amherstburg, ON",
  "Windsor, ON",
  "Tecumseh, ON",
  "LaSalle, ON",
  "Wheatley, ON",
  "Tillsonburg, ON",
  "Aylmer, ON",
  "St. Thomas, ON",
  "London, ON",
  "Ingersoll, ON",
  "Tavistock, ON",
  "Listowel, ON",
  "Palmerston, ON",
  "Mount Forest, ON",
  "Fergus, ON",
  "Elora, ON",
  "Arthur, ON",
  "Harriston, ON",
  "Walkerton, ON",
  "Kincardine, ON",
  "Port Elgin, ON",
  "Southampton, ON",
  "Tiverton, ON",
  "Hanover, ON",
  "Durham, ON",
  "Owen Sound, ON",
  "Meaford, ON",
  "Thornbury, ON",
  "Collingwood, ON",
  "Wasaga Beach, ON",
  "Midland, ON",
  "Penetanguishene, ON",
  "Victoria Harbour, ON",
  "Port McNicoll, ON",
  "Orillia, ON",
  "Gravenhurst, ON",
  "Bracebridge, ON",
  "Huntsville, ON",
  "Bancroft, ON",
  "Madoc, ON",
  "Tweed, ON",
  "Deseronto, ON",
  "Brighton, ON",
  "Cobourg, ON",
  "Port Hope, ON",
  "Lindsay, ON",
  "Fenelon Falls, ON",
  "Bobcaygeon, ON",
  "Haliburton, ON",
  "Minden, ON",
  "Bancroft, ON",
  "Madoc, ON",
  "Trenton, ON",
  "Belleville, ON",
  "Picton, ON",
  "Wellington, ON",
  "Consecon, ON",
  "Bloomfield, ON",
  // Quebec
  "Montreal, QC",
  "Quebec City, QC",
  "Laval, QC",
  "Gatineau, QC",
  "Longueuil, QC",
  "Sherbrooke, QC",
  "Saguenay, QC",
  "Lévis, QC",
  "Trois-Rivières, QC",
  "Terrebonne, QC",
  "Repentigny, QC",
  "Saint-Jean-sur-Richelieu, QC",
  "Brossard, QC",
  "Drummondville, QC",
  "Saint-Jérôme, QC",
  "Granby, QC",
  "Beloeil, QC",
  "Saint-Hyacinthe, QC",
  "Rimouski, QC",
  "Rivière-du-Loup, QC",
  "Matane, QC",
  "Amqui, QC",
  "Mont-Joli, QC",
  "Sept-Îles, QC",
  "Baie-Comeau, QC",
  "Havre-Saint-Pierre, QC",
  "Port-Cartier, QC",
  "Alma, QC",
  "Dolbeau-Mistassini, QC",
  "Chibougamau, QC",
  "Rouyn-Noranda, QC",
  "Val-d'Or, QC",
  "Amos, QC",
  "La Sarre, QC",
  "Ville-Marie, QC",
  "Saint-Eustache, QC",
  "Mascouche, QC",
  "Boucherville, QC",
  "Châteauguay, QC",
  "Vaudreuil-Dorion, QC",
  "Salaberry-de-Valleyfield, QC",
  "Saint-Constant, QC",
  "Candiac, QC",
  "La Prairie, QC",
  "Carignan, QC",
  "Chambly, QC",
  "Farnham, QC",
  "Cowansville, QC",
  "Sainte-Julie, QC",
  "Beloeil, QC",
  "Sorel-Tracy, QC",
  "Joliette, QC",
  "Rawdon, QC",
  "Saint-Gabriel-de-Valcartier, QC",
  "Beauport, QC",
  "Charlesbourg, QC",
  "Limoilou, QC",
  "Sainte-Foy, QC",
  "Lévis, QC",
  "Thetford Mines, QC",
  "Victoriaville, QC",
  "Plessisville, QC",
  "Asbestos, QC",
  "Magog, QC",
  "Coaticook, QC",
  "Lac-Mégantic, QC",
  "Gaspé, QC",
  "Percé, QC",
  "Carleton-sur-Mer, QC",
  "New Richmond, QC",
  "Bonaventure, QC",
  "Maria, QC",
  "Cap-Chat, QC",
  "Sainte-Anne-des-Monts, QC",
  "New Carlisle, QC",
  "Paspébiac, QC",
  "Chandler, QC",
  "Murdochville, QC",
  "Hull, QC",
  "Gatineau, QC",
  "Buckingham, QC",
  "Masson-Angers, QC",
  "Aylmer, QC",
  "Maniwaki, QC",
  "Grand-Remous, QC",
  "Mont-Laurier, QC",
  "Rivière-Rouge, QC",
  "Sainte-Agathe-des-Monts, QC",
  "Saint-Sauveur, QC",
  "Saint-Jovite, QC",
  "Val-David, QC",
  "Lachute, QC",
  "Saint-André-d'Argenteuil, QC",
  "Hawkesbury, ON",
  // New Brunswick
  "Saint John, NB",
  "Moncton, NB",
  "Fredericton, NB",
  "Dieppe, NB",
  "Miramichi, NB",
  // Nova Scotia
  "Halifax, NS",
  "Dartmouth, NS",
  "Sydney, NS",
  "Truro, NS",
  "New Glasgow, NS",
  // Prince Edward Island
  "Charlottetown, PE",
  "Summerside, PE",
  // Newfoundland and Labrador
  "St. John's, NL",
  "Mount Pearl, NL",
  "Corner Brook, NL",
  "Conception Bay South, NL",
  // Yukon
  "Whitehorse, YT",
  // Northwest Territories
  "Yellowknife, NT",
  // Nunavut
  "Iqaluit, NU",
];

// Map city name (lowercase) -> province abbreviation for video-mode search
export const cityToProvince: Record<string, string> = {};
cities.forEach((c) => {
  const idx = c.lastIndexOf(", ");
  if (idx === -1) return;
  const city = c.slice(0, idx).trim();
  const prov = c.slice(idx + 2).trim();
  if (city && prov) cityToProvince[city.toLowerCase()] = prov;
});
